services:
  service:
    build: ./service
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
    volumes:
      - news-storage:/news
    secrets:
      - novosti-admin-token
    environment:
      STORAGE_DIR: /news
      REDIS_ADDR: "redis:6379"
      ADMIN_TOKEN_FILE: /run/secrets/novosti-admin-token
    ports:
      - "80:9000"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
  bot:
    build: ./bot
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
    secrets:
      - novosti-admin-token
    environment:
      TASK_URL: https://novosti-3d5d54b8c9f9f81aabcf60563021845f.ctfcup-2023.ru
      REDIS_URL: redis://redis:6379
      ADMIN_TOKEN_FILE: /run/secrets/novosti-admin-token
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
  files:
    build: ./files
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 128M
    secrets:
      - source: novosti-flag
        target: /static/flag
    restart: unless-stopped
  redis:
    image: redis:7.2.2-alpine3.18
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 3s
    restart: unless-stopped
secrets:
  novosti-flag:
    file: ./novosti-flag
  novosti-admin-token:
    file: ./novosti-admin-token
volumes:
  news-storage:
