version: "2.4"
services:
  pwn:
    build: .
    image: "cr.yandex/crp56e8fvolm1rqugnkf/pwn-ella:latest"
    ports:
      - "13000:13000"
    restart: unless-stopped
    cpus: 1
    pids_limit: 64
    mem_limit: 512m
    healthcheck:
      test: ["CMD", "/bin/sh", "-c", "[ \"$(sha256sum ./flag.txt | awk '{print $1}')\" = \"4748008ef03d4ee310e863f55e820515c4337f6afcc3767f2fde27826e91644a\" ] || kill 1"]
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 10s
