version: '3'

services:
  api-server:
    build:
      context: ./api-server
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      MONGO_USERNAME: root
      MONGO_PASSWORD: af78cd202135e0a016d65fe149ac6e4a
      MONGO_DB: my_database
      SECRET_KEY: AMOGUSAMOGUSAISBDKASUVFJCASVKBJJKHVJG


  static-server:
    build:
      context: ./static-server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: af78cd202135e0a016d65fe149ac6e4a
      MONGO_INITDB_DATABASE: my_database
    ports:
      - "27017:27017"
